// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.21;

import {IVerifier} from "./IVerifier.sol";

/// @title ComplianceDefinition
/// @notice The stable on-chain representation of a compliance definition. Regulators deploy
///  one contract per compliance definition, and applications reference its address to enforce
///  compliance. The address remains constant even as the underlying verification logic or
///  public parameters are updated, so applications never need to change their reference.
/// @dev Each update to a compliance definition, whether a constraint update or a public
///  parameter update, is recorded as a new `ComplianceVersion` entry. This append-only
///  history provides a complete audit trail and enables verification against any historical
///  state of the definition. Versions are scoped to block-height windows (`tStart`, `tEnd`),
///  allowing definitions to be published before they take effect and enabling users to prove
///  compliance against past regulations.
contract ComplianceDefinition {
    /// @notice Captures the complete state of a compliance definition at a point in time.
    /// @dev A new `ComplianceVersion` is appended on every call to `updateCircuit` or
    ///  `updateParams`. The version history is never modified, only extended.
    /// @param verifier Address of the ZK verifier contract containing the verification key
    ///  for the compliance circuit. Changes only on constraint updates.
    /// @param merkleRoot Merkle root commitment to the public parameters (e.g., a sanction
    ///  list). The full parameter set is stored off-chain and referenced via `metadataHash`.
    ///  Committing only the root keeps on-chain storage costs constant regardless of parameter
    ///  set size.
    /// @param tStart Block height at which this version becomes active.
    /// @param tEnd Block height at which this version expires.
    /// @param metadataHash IPFS content hash linking to the circuit to be proved
    /// @param leavesHash IPFS content hash of the Merkle tree leaves, allowing users to
    ///  reconstruct the tree and generate inclusion/exclusion proofs locally.
    struct ComplianceVersion {
        address verifier;
        bytes32 merkleRoot;
        uint256 tStart;
        uint256 tEnd;
        string metadataHash;
        string leavesHash;
    }

    /// @notice Append-only array of all compliance definition versions, serving as a
    ///  complete audit trail.
    ComplianceVersion[] public versions;

    /// @notice The address authorized to update this compliance definition.
    /// @dev In practice this is the regulatory body or blockchain analytics company
    ///  responsible for maintaining the definition (e.g., updating sanction lists).
    address public regulator;

    /// @notice Human-readable name identifying this compliance definition.
    string public name;

    /// @notice Thrown when a non-regulator address attempts to call a regulator-only function.
    error NotRegulator();

    /// @notice Thrown when no version is active at the current block height.
    error NoActiveVersion();

    /// @notice Thrown when no version is active at the requested block height.
    /// @param blockHeight The queried block height for which no version was found.
    error NoVersionAtBlock(uint256 blockHeight);

    /// @notice Restricts access to the regulator address.
    modifier onlyRegulator() {
        if (msg.sender != regulator) revert NotRegulator();
        _;
    }

    /// @notice Deploys a new compliance definition owned by `_regulator`.
    /// @dev The contract is deployed with no versions. The regulator must call
    ///  `updateCircuit` to publish the first version before the definition can be used.
    /// @param _regulator The address authorized to manage this compliance definition.
    /// @param _name Human-readable name for this compliance definition.
    constructor(address _regulator, string memory _name) {
        regulator = _regulator;
        name = _name;
    }

    /// @notice Verifies a user's zero-knowledge proof of compliance against the currently
    ///  active version of this definition.
    /// @dev Applications integrate with this framework by calling `verify` at entry-point
    ///  functions (e.g., `deposit(someVars, proof)`). If the proof does not verify, the
    ///  transaction reverts, providing proactive compliance: non-compliant actions are
    ///  prevented rather than detected after the fact.
    ///
    ///  The proof is verified against two public inputs:
    ///   1. `msg.sender` — binds the proof to the caller's address, preventing proof replay.
    ///   2. `merkleRoot` — binds the proof to the current public parameter set.
    /// @param proof The serialized zero-knowledge proof generated by the user's proof manager.
    /// @return True if the proof is valid, indicating the caller is compliant.
    function verify(bytes calldata proof) external returns (bool) {
        ComplianceVersion memory v = getActiveVersion();
        bytes32[] memory publicInputs = new bytes32[](2);
        publicInputs[0] = bytes32(uint256(uint160(msg.sender)));
        publicInputs[1] = v.merkleRoot;
        return IVerifier(v.verifier).verify(proof, publicInputs);
    }

    /// @notice Publishes a new version with an updated constraint (circuit) and verifier.
    /// @dev Used when the compliance logic itself changes — for example, adding or removing
    ///  a constraint from the definition. Because this changes the circuit, a new verifier
    ///  contract with the updated verification key must be deployed first. The previous
    ///  version remains in history for audit and historical verification purposes.
    /// @param newVerifier Address of the newly deployed ZK verifier contract.
    /// @param newMerkleRoot Merkle root of the public parameter set for this version.
    /// @param tStart Block height at which this version becomes active. Can be set in the
    ///  future to allow publishing before the definition takes effect.
    /// @param tEnd Block height at which this version expires.
    /// @param metadataHash IPFS hash of the compliance circuit to be proved
    /// @param leavesHash IPFS hash of the Merkle tree leaves.
    function updateCircuit(
        address newVerifier,
        bytes32 newMerkleRoot,
        uint256 tStart,
        uint256 tEnd,
        string calldata metadataHash,
        string calldata leavesHash
    ) external onlyRegulator {
        versions.push(
            ComplianceVersion({
                verifier: newVerifier,
                merkleRoot: newMerkleRoot,
                tStart: tStart,
                tEnd: tEnd,
                metadataHash: metadataHash,
                leavesHash: leavesHash
            })
        );
    }

    /// @notice Publishes a new version with updated public parameters, reusing the current
    ///  verifier (circuit unchanged).
    /// @dev Used when only the public parameters change — for example, adding an address to
    ///  a sanction list. The circuit and verifier remain the same, so users only need to
    ///  re-prove constraints affected by the parameter change, not the entire definition.
    /// @param newMerkleRoot Merkle root of the updated public parameter set.
    /// @param newLeavesHash IPFS hash of the updated Merkle tree leaves.
    function updateParams(
        bytes32 newMerkleRoot,
        string calldata newLeavesHash
    ) external onlyRegulator {
        ComplianceVersion memory current = getActiveVersion();
        versions.push(
            ComplianceVersion({
                verifier: current.verifier,
                merkleRoot: newMerkleRoot,
                tStart: current.tStart,
                tEnd: current.tEnd,
                metadataHash: current.metadataHash,
                leavesHash: newLeavesHash
            })
        );
    }

    /// @notice Returns the compliance version that is active at the current block height.
    /// @dev Iterates backwards through the version array to return the most recently
    ///  published version whose validity window contains `block.number`. Reverts if no
    ///  version is currently active.
    /// @return The `ComplianceVersion` active at the current block.
    function getActiveVersion() public view returns (ComplianceVersion memory) {
        uint256 len = versions.length;
        for (uint256 i = len; i > 0; i--) {
            ComplianceVersion memory v = versions[i - 1];
            if (v.tStart <= block.number && block.number <= v.tEnd) {
                return v;
            }
        }
        revert NoActiveVersion();
    }

    /// @notice Returns the compliance version that was active at a given block height.
    /// @dev Enables historical verification — users can prove they were compliant with a
    ///  regulation at a previous point in time by retrieving the version that was active
    ///  then. Iterates backwards to return the most recently published matching version.
    /// @param blockHeight The block height to query.
    /// @return The `ComplianceVersion` that was active at `blockHeight`.
    function getVersionAt(
        uint256 blockHeight
    ) external view returns (ComplianceVersion memory) {
        uint256 len = versions.length;
        for (uint256 i = len; i > 0; i--) {
            ComplianceVersion memory v = versions[i - 1];
            if (v.tStart <= blockHeight && blockHeight <= v.tEnd) {
                return v;
            }
        }
        revert NoVersionAtBlock(blockHeight);
    }

    /// @notice Returns the total number of versions that have been published.
    /// @dev Useful for enumerating the full audit trail of this compliance definition.
    /// @return The number of `ComplianceVersion` entries in the history.
    function getVersionCount() external view returns (uint256) {
        return versions.length;
    }
}
