// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.21;

import {ComplianceDefinition} from "./ComplianceDefinition.sol";

/// @title CompliantToken
/// @notice A minimal ERC-20 token that gates minting behind a compliance proof.
///  Users must supply a valid zero-knowledge proof of compliance to mint tokens.
///  The proof is verified atomically by the referenced ComplianceDefinition contract.
contract CompliantToken {
    ComplianceDefinition public immutable complianceDefinition;

    string public name;
    string public symbol;
    uint8 public constant decimals = 18;
    uint256 public totalSupply;

    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    error ComplianceCheckFailed();

    constructor(address _complianceDefinition, string memory _name, string memory _symbol) {
        complianceDefinition = ComplianceDefinition(_complianceDefinition);
        name = _name;
        symbol = _symbol;
    }

    /// @notice Mint 1 token to the caller after verifying their compliance proof.
    /// @param proof The serialized zero-knowledge proof generated by the caller's proof manager.
    function mint(bytes calldata proof) external {
        bool valid = complianceDefinition.verify(proof);
        if (!valid) revert ComplianceCheckFailed();

        uint256 amount = 1e18;
        totalSupply += amount;
        balanceOf[msg.sender] += amount;
        emit Transfer(address(0), msg.sender, amount);
    }

    function transfer(address to, uint256 value) external returns (bool) {
        balanceOf[msg.sender] -= value;
        balanceOf[to] += value;
        emit Transfer(msg.sender, to, value);
        return true;
    }

    function approve(address spender, uint256 value) external returns (bool) {
        allowance[msg.sender][spender] = value;
        emit Approval(msg.sender, spender, value);
        return true;
    }

    function transferFrom(address from, address to, uint256 value) external returns (bool) {
        allowance[from][msg.sender] -= value;
        balanceOf[from] -= value;
        balanceOf[to] += value;
        emit Transfer(from, to, value);
        return true;
    }
}
